export const FETCH_USER = 'FETCH_USER';

export const FETCH_PLAYER = 'FETCH_PLAYER';

export const DB_COUNT = 'DB_COUNT';
export const LOAD_LIBRARY_PAGE = 'LOAD_LIBRARY_PAGE';
export const FETCH_LIBRARY = 'FETCH_LIBRARY';

export const RETRIEVE_AUTH_TOKEN = 'RETRIEVE_AUTH_TOKEN';

export const FIRST_PAGE = 'FIRST_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';

export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const APPEND_PLAYLISTS = 'APPEND_PLAYLISTS';

export const FETCH_PLAY_STATE = 'FETCH_PLAY_STATE';

export const TOGGLE_CONFIG = 'TOGGLE_CONFIG';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
